#!/bin/sh

# regular expresion to filter files that will be checked
# example: REG_EXP=" | grep -v '^database/\|app/Http/routes.php$' | grep \\.php$";
REG_EXP=" | grep \\.php$";

PROJECT=`php -r "echo dirname(dirname(dirname(realpath('$0'))));"`
STAGED_FILES_CMD="git diff --cached --name-only --diff-filter=ACMR HEAD"${REG_EXP}
STAGED_FILES="$(eval ${STAGED_FILES_CMD})"

# Determine if a file list is passed
if [ "$#" -eq 1 ]
then
    oIFS=$IFS
    IFS='
    '
    SFILES="$1"
    IFS=$oIFS
fi
SFILES=${SFILES:-$STAGED_FILES}

echo "Checking files..."
for FILE in $SFILES
do
    php -l -d display_errors=0 $PROJECT/$FILE 1> /dev/null
    if [ $? != 0 ]
    then
        echo "Fix the error before commit."
        exit 1
    fi
    FILES="$FILES $PROJECT/$FILE"
done

if [ "$FILES" != "" ]
then
    ./vendor/bin/phpcs --standard=PSR2 --encoding=utf-8 -n -p $FILES
    if [ $? != 0 ]
    then
        echo "Fix the error before commit!"
        exit 1
    fi
fi

exit $?